dataset: s1 # ['s1', 's2']
run_index: 1 # 0 for random trials, 1 for bayesian opt (requires 10+ previous runs)
max_evals: 7 # max number of evaluations per run
experiment_name: unet_shift_nodem_all # name of tuning experiments (will be directory where results are saved)
early_stopping: True # early stopping for bayesian opt
patience: 30
random_state: 9830