format: tif # prediction label format: ['tif', 'npy']
replace: true # whether to overwrite pre-existing predictions
data_dir: ${paths.imagery_dir}/areas/20180908_281_832/ # directory with rasters to make predictions in
threshold: 0.8769 # threshold for classifying a positive prediction
batch_size: 256
filter_type: cvae
n_workers: 8
threads_per_worker: 16

# 20180815_304_700
# 20230103_373_813
# 20180908_281_832