format: tif # prediction label format: ['tif', 'npy']
replace: true # whether to overwrite pre-existing predictions
data_dir: ${paths.imagery_dir}/areas/20240718_188_887/ # directory with rasters to make predictions in
threshold: 0.75 # threshold for classifying a positive prediction
batch_size: 256
n_workers: 8
threads_per_worker: 16

# S2
# 20220729_273_855 - haze
# 20170830_482_704 - urban
# 20240718_188_887 - cloud + shadow