# For preprocess_s2.py script that only preprocesses manual labels
# This is the v2.4 (FINAL V2) dataset with texas, illinois, others, and sar_coincident labels
# Adds one new tile to training and one new tile to validation
# Latest as of 12/3/25
s2:
  label_splits:
    train: [
      "texas/label_20160314_20160311_452_846.tif",
      "texas/label_20160314_20160311_452_845.tif",
      "texas/label_20160314_20160311_464_837.tif",
      "texas/label_20160314_20160311_453_845.tif",
      "texas/label_20160314_20160311_451_839.tif",
      "texas/label_20160314_20160311_452_843.tif",
      "texas/label_20160314_20160311_451_838.tif",
      "texas/label_20160307_20160311_452_846.tif",
      "texas/label_20170830_20170828_463_695.tif",
      "texas/label_20170830_20170828_482_695.tif",
      "texas/label_20170830_20170828_484_696.tif",
      "texas/label_20170830_20170826_489_703.tif",
      "texas/label_20170830_20170826_493_695.tif",
      "texas/label_20170830_20170826_493_708.tif",
      "texas/label_20170830_20170826_488_695.tif",
      "texas/label_20170830_20170828_462_695.tif",
      "texas/label_20170830_20170826_487_696.tif",
      "texas/label_20170830_20170829_497_709.tif",
      "texas/label_20170830_20170828_470_694.tif",
      "texas/label_20170830_20170826_487_695.tif",
      "texas/label_20170830_20170826_490_704.tif",
      "texas/label_20170830_20170826_497_697.tif",
      "texas/label_20170830_20170826_505_698.tif",
      "texas/label_20151112_20151109_473_940.tif",
      "texas/label_20151112_20151109_473_941.tif",
      "texas/label_20151112_20151109_474_941.tif",
      "texas/label_20151112_20151109_472_940.tif",
      "texas/label_20151112_20151109_473_939.tif",
      "texas/label_20151112_20151109_485_960.tif",
      "texas/label_20151112_20151109_474_942.tif",
      "texas/label_20150919_20150917_497_811.tif",
      "texas/label_20150919_20150917_496_812.tif",
      "texas/label_20150919_20150917_497_812.tif",
      "texas/label_20150919_20150917_496_811.tif",
      "texas/label_20180824_20180822_580_1050.tif",
      "texas/label_20180824_20180822_586_1051.tif",
      "texas/label_20180818_20180815_304_703.tif",
      "illinois/label_20190409_20190408_204_815.tif",
      "illinois/label_20190409_20190408_205_815.tif",
      "illinois/label_20240520_20240521_193_764.tif",
      "illinois/label_20240515_20240521_195_769.tif",
      "illinois/label_20220811_20220808_183_852.tif",
      "illinois/label_20220811_20220808_183_853.tif",
      "illinois/label_20220811_20220808_183_851.tif",
      "illinois/label_20220811_20220808_183_850.tif",
      "illinois/label_20190317_20190317_180_864.tif",
      "illinois/label_20190317_20190317_179_859.tif",
      "illinois/label_20190317_20190317_179_861.tif",
      "illinois/label_20190317_20190317_181_857.tif",
      "illinois/label_20190317_20190317_180_860.tif",
      "illinois/label_20190317_20190317_180_859.tif",
      "illinois/label_20190317_20190317_182_856.tif",
      "illinois/label_20190317_20190317_180_863.tif",
      "illinois/label_20190317_20190317_179_862.tif",
      "illinois/label_20190916_20190912_172_815.tif",
      "illinois/label_20190916_20190912_175_823.tif",
      "illinois/label_20190325_20190325_201_832.tif",
      "illinois/label_20190325_20190325_202_832.tif",
      "illinois/label_20190325_20190325_203_829.tif",
      "illinois/label_20190325_20190325_202_826.tif",
      "illinois/label_20181008_20181008_182_855.tif",
      "illinois/label_20181008_20181008_179_862.tif",
      "illinois/label_20230925_20230922_237_858.tif",
      "others/label_20180705_20180705_201_906.tif",
      "others/label_20190419_20190419_181_879.tif",
      "others/label_20210803_20210803_187_893.tif",
      "others/label_20211007_20211007_222_850.tif",
      "others/label_20230208_20230208_270_661.tif",
      "others/label_20230510_20230510_266_837.tif",
      "others/label_20240921_20240921_194_892.tif",
      "others/label_20200904_20200904_279_941.tif",
      "others/label_20200904_20200904_279_943.tif",
      "others/label_20200815_20200815_307_896.tif",
      "others/label_20210902_20210902_264_834.tif",
      "others/label_20210831_20210831_239_806.tif",
      "others/label_20230604_20230604_249_871.tif",
      "others/label_20230604_20230604_193_888.tif",
      "others/label_20210704_20210704_189_881.tif",
      "others/label_20190715_20190715_190_886.tif",
      "others/label_20190715_20190715_190_889.tif",
      "others/label_20230704_20230704_193_885.tif",
      "others/label_20231007_20231007_196_880.tif",
      "others/label_20220927_20220927_195_888.tif",
      "sar_coincident/label_20160816_20160811_115_698.tif",
      "sar_coincident/label_20160925_20160921_320_1176.tif",
      "sar_coincident/label_20170105_20170102_444_914.tif",
      "sar_coincident/label_20170610_20170606_442_855.tif",
      "sar_coincident/label_20170708_20170703_291_770.tif",
      "sar_coincident/label_20170710_20170706_275_1149.tif",
      "sar_coincident/label_20170802_20170729_258_1150.tif",
      "sar_coincident/label_20170830_20170826_481_693.tif",
      "sar_coincident/label_20170830_20170826_483_692.tif",
      "sar_coincident/label_20170830_20170826_494_694.tif",
      "sar_coincident/label_20170830_20170826_501_682.tif",
      "sar_coincident/label_20170830_20170826_510_684.tif",
      "sar_coincident/label_20170830_20170826_510_685.tif",
      "sar_coincident/label_20170830_20170828_459_696.tif",
      "sar_coincident/label_20170830_20170829_504_711.tif",
      "sar_coincident/label_20171025_20171023_468_860.tif",
      "sar_coincident/label_20180402_20180329_463_714.tif",
      "sar_coincident/label_20180414_20180410_486_1027.tif",
      "sar_coincident/label_20180414_20180410_490_1036.tif",
      "sar_coincident/label_20180624_20180619_539_645.tif",
      "sar_coincident/label_20180824_20180822_586_1053.tif",
      "sar_coincident/label_20180903_20180901_235_1165.tif",
      "sar_coincident/label_20180916_20180911_491_721.tif",
      "sar_coincident/label_20180916_20180911_497_716.tif",
      "sar_coincident/label_20180924_20180922_354_702.tif",
      "sar_coincident/label_20181029_20181025_496_715.tif",
      "sar_coincident/label_20181210_20181208_477_724.tif",
      "sar_coincident/label_20200918_20200917_403_974.tif",
      "sar_coincident/label_20210129_20210128_339_94.tif",
      "sar_coincident/label_20210303_20210301_312_915.tif",
      "sar_coincident/label_20210825_20210822_230_1213.tif",
      "sar_coincident/label_20230108_20230103_380_799.tif",
      "sar_coincident/label_20230829_20230824_203_1029.tif",
      "clouds/label_20190617_20190616_180_985.tif",
      "clouds/label_20190502_20190428_119_776.tif",
      "clouds/label_20211210_20211210_71_720.tif",
      "clouds/label_20210323_20210318_445_905.tif",
      "clouds/label_20180223_20180220_166_1139.tif",
      "clouds/label_20231227_20231226_62_187.tif",
      "clouds/label_20240305_20240304_177_1217.tif",
      "clouds/label_20210213_20210209_439_329.tif",
      "clouds/label_20211215_20211210_71_720.tif",
      "clouds/label_20200312_20200307_275_707.tif",
      "clouds/label_20210106_20210104_177_1096.tif",
      "clouds/label_20240418_20240416_261_690.tif",
      "clouds/label_20200131_20200126_112_596.tif",
      "clouds/label_20181201_20181129_165_681.tif",
      "clouds/label_20230102_20230101_404_877.tif",
      "clouds/label_20230805_20230802_110_646.tif",
      "clouds/label_20230102_20221229_259_38.tif",
      "clouds/label_20231002_20231001_34_65.tif",
      "clouds/label_20240627_20240627_394_977.tif",
      "clouds/label_20210331_20210328_266_1180.tif",
      "clouds/label_20220414_20220414_124_756.tif",
      "clouds/label_20241103_20241029_63_589.tif",
      "clouds/label_20200122_20200121_420_717.tif",
      "clouds/label_20240305_20240229_260_1158.tif",
      "clouds/label_20220501_20220428_111_826.tif",
      "clouds/label_20230104_20230104_300_1012.tif",
      "clouds/label_20240504_20240430_349_569.tif",
      "clouds/label_20220416_20220414_438_967.tif",
      "clouds/label_20230919_20230917_191_948.tif",
      "clouds/label_20211114_20211113_288_1119.tif",
      "clouds/label_20211219_20211214_104_828.tif",
      "clouds/label_20210527_20210523_180_691.tif",
      "clouds/label_20240315_20240314_293_1132.tif"
    ]
    val: [
      "texas/label_20190908_20190906_396_1099.tif",
      "texas/label_20190908_20190906_375_1133.tif",
      "texas/label_20180918_20180917_389_1098.tif",
      "texas/label_20240505_20240505_464_712.tif",
      "texas/label_20240505_20240505_465_713.tif",
      "illinois/label_20180225_20180225_206_863.tif",
      "illinois/label_20180225_20180225_206_876.tif",
      "illinois/label_20191008_20191008_182_862.tif",
      "sar_coincident/label_20210727_20210727_555_1038.tif",
      "sar_coincident/label_20210902_20210830_474_820.tif",
      "others/label_20180924_20180924_145_810.tif",
      "others/label_20190710_20190710_184_887.tif",
      "others/label_20200701_20200701_288_897.tif",
      "others/label_20190710_20190710_324_846.tif",
      "others/label_20230520_20230520_191_886.tif",
      "clouds/label_20181215_20181213_180_561.tif",
      "clouds/label_20210225_20210220_448_693.tif",
      "clouds/label_20181127_20181123_239_864.tif",
      "clouds/label_20240927_20240925_367_1008.tif",
      "clouds/label_20231004_20231001_34_65.tif",
      "clouds/label_20201027_20201027_196_1154.tif",
      "clouds/label_20211214_20211214_104_828.tif",
      "clouds/label_20190508_20190503_85_952.tif",
      "clouds/label_20240218_20240217_388_986.tif",
      "clouds/label_20230109_20230104_300_1012.tif",
      "clouds/label_20211011_20211009_177_399.tif",
      "clouds/label_20190328_20190324_277_783.tif",
      "clouds/label_20240326_20240322_251_1047.tif",
      "clouds/label_20190309_20190309_145_699.tif",
      "clouds/label_20240317_20240316_483_830.tif",
      "clouds/label_20220203_20220129_276_963.tif"
    ]
    test: [
      "texas/label_20170904_20170830_482_705.tif",
      "texas/label_20170904_20170830_482_704.tif",
      "texas/label_20190921_20190921_476_748.tif",
      "texas/label_20190921_20190921_473_739.tif",
      "texas/label_20190921_20190921_476_747.tif",
      "illinois/label_20190903_20190901_246_848.tif",
      "illinois/label_20180304_20180302_208_907.tif",
      "illinois/label_20180304_20180302_207_908.tif",
      "others/label_20190322_20190322_225_849.tif",
      "others/label_20240409_20240409_212_893.tif",
      "others/label_20190401_20190401_315_861.tif",
      "others/label_20240718_20240718_188_887.tif",
      "others/label_20220729_20220729_273_855.tif",
      "others/label_20220729_20220729_197_884.tif",
      "others/label_20220729_20220729_273_844.tif",
      "clouds/label_20181129_20181129_165_681.tif",
      "clouds/label_20190221_20190218_417_677.tif",
      "clouds/label_20210608_20210605_51_732.tif",
      "clouds/label_20200310_20200307_275_707.tif",
      "clouds/label_20190825_20190824_210_754.tif",
      "clouds/label_20170527_20170523_123_787.tif",
      "clouds/label_20230420_20230415_102_901.tif",
      "clouds/label_20190219_20190218_417_677.tif",
      "clouds/label_20190922_20190922_151_93.tif",
      "clouds/label_20210401_20210330_563_629.tif",
      "clouds/label_20241104_20241103_46_770.tif",
      "clouds/label_20230323_20230319_296_580.tif",
      "clouds/label_20220414_20220414_438_967.tif",
      "clouds/label_20200101_20191230_201_26.tif",
      "clouds/label_20190430_20190428_119_776.tif",
      "clouds/label_20200303_20200227_451_557.tif",
      "clouds/label_20181101_20181028_234_1018.tif",
      "clouds/label_20190325_20190324_277_783.tif"
    ]
  sample_dirs:
    - "s2_clouds_99pct_0_5"
    - "s2_manual_2_4_100_others"
    - "s2_manual_6_4_35_texas"
    - "s2_manual_7_4_10_illinois"
    - "s2_manual_0_5_15_precip"

size: 64
seed: 102003
method: strided
samples:
stride: 16
suffix: all_clouds_v2-4
n_workers: 24