save_dir: ${paths.benchmarks_dir}/s2_models # directory where csvs are saved
trials: 10 # total number of trials per benchmark
max_evals: 10 # max number of evaluations per script run (<trials if walltime is limiting)
config_id: s2_unet_noindices # unique identifier for this benchmark configuration
description: "Sentinel-2 UNet tuned with improved dropout and only the 6 S2 spectral bands (no water indices)." # optional description
seed: 77332 # master random seed for reproducibility