area_id: # identifier for the area
shapefile: # path to shapefile of study area
start_date: # date of flood event in format YYYY-MM-DD
end_date: # date of flood event in format YYYY-MM-DD
product_ids_s2: [] # if want a specific product id to match
product_ids_s1: [] # if want a specific product id to match
dir_path: # directory where downloaded imagery will be saved
crs: # optional CRS to force the imagery to
include_cmap: true # whether to include color maps for the rasters
source: cdse # source of the data ['mpc', 'aws', 'cdse']