defaults:
  - paths: default
  - analysis:
  - sampling:
  - preprocess:
  - inference: inference_sar # conduct inference using S1 UNet++
  - tuning:
  - benchmarking:
  - ad:
  - s1_unetpp_all_best # load example model settings
  - _self_

# hydra config
hydra:
  # output_subdir: null -> disable hydra completely
  run:
    dir: ${paths.base_dir}/hydra # keeps hydra outputs from cluttering directory